name: Rock Build

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      artifact-name:
        description: Name of the artifact
        required: true
        type: string
      path:
        description: Path to the rockcraft.yaml file
        required: true
        type: string

jobs:
  build-rock:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: canonical/craft-actions/rockcraft-pack@91513c1bae43bc871c85ea2fdf2ac7eed91034f9 # main
        id: rockcraft
        with:
          rockcraft-channel: edge
          path: ${{ inputs.path }}

      - name: Upload container image to GitHub Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ steps.rockcraft.outputs.rock }}
